# 更新 fork (上游原始仓库已清库，改为手动触发)
name: update fork

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id == github.event.sender.id && github.actor != 'gedoor' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set env
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
    - name: Update fork
      run: |
        git remote add upstream https://github.com/huajideshutiao/legado.git
        git remote -v
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push origin master
